### PR TITLE
Set no bias for raw kernel

### PR DESCRIPTION
**Pull request by dieris**

### CODE REVIEW

**Comment by caryan** [comment]
@dieris  are you sure?  Aren't raw kernel integrator streams (a,0,b)?

**Comment by caryan** [comment]
Uh actually there are bigger problems here. There's a copy-paste error in the if side too.

**Comment by dieris** [comment]
oops, ok, I thought there was something wrong...

**Comment by caryan** [comment]
Should be better after this  609595a

**Pull request merged**
